import type { Metadata } from "next";
import { DirectoryClient } from "./DirectoryClient";

export const metadata: Metadata = {
  title: "Worldwide Job Board Directory",
  description:
    "A searchable directory of LinkedIn, Indeed, and similar job-finding websites around the world.",
};

const jobBoards = [
  {
    name: "LinkedIn Jobs",
    url: "https://www.linkedin.com/jobs/",
    region: "Global",
    coverageRegions: [
      "United States",
      "Canada",
      "United Kingdom",
      "Europe",
      "Australia",
      "India",
      "Asia Pacific",
      "Middle East",
      "Africa",
      "Latin America",
    ],
    focus: "General",
    type: "Network",
    goodFor: "Large employers, networking, recruiter discovery, alumni searches.",
    notes: "Best when your profile is polished and you want recruiter visibility.",
  },
  {
    name: "Indeed",
    url: "https://www.indeed.com/",
    region: "Global",
    coverageRegions: [
      "United States",
      "Canada",
      "United Kingdom",
      "Europe",
      "Australia",
      "India",
      "Asia Pacific",
      "Middle East",
      "Africa",
      "Latin America",
    ],
    focus: "General",
    type: "Aggregator",
    goodFor: "High-volume job search across industries and experience levels.",
    notes: "Use country-specific Indeed domains for better local results.",
  },
  {
    name: "Glassdoor",
    url: "https://www.glassdoor.com/Job/",
    region: "Global",
    coverageRegions: ["United States", "Canada", "United Kingdom", "Europe", "Australia", "India"],
    focus: "General",
    type: "Research",
    goodFor: "Combining job listings with company reviews and salary research.",
    notes: "Useful before interviews and offer negotiation.",
  },
  {
    name: "Google Jobs",
    url: "https://www.google.com/search?q=jobs+near+me",
    region: "Global",
    coverageRegions: [
      "United States",
      "Canada",
      "United Kingdom",
      "Europe",
      "Australia",
      "India",
      "Asia Pacific",
      "Middle East",
      "Africa",
      "Latin America",
    ],
    focus: "General",
    type: "Aggregator",
    goodFor: "Fast discovery from many boards and company career pages.",
    notes: "Search from Google with role plus location, for example: data analyst Canada jobs.",
  },
  {
    name: "ZipRecruiter",
    url: "https://www.ziprecruiter.com/",
    region: "United States",
    focus: "General",
    type: "Aggregator",
    goodFor: "US roles, quick applications, job alerts, and broad employer coverage.",
    notes: "Strong for business, operations, service, and tech roles in the US.",
  },
  {
    name: "Monster",
    url: "https://www.monster.com/",
    region: "Global",
    coverageRegions: ["United States", "Canada", "United Kingdom", "Europe", "India"],
    focus: "General",
    type: "Job board",
    goodFor: "Traditional job search, resume posting, and alerts.",
    notes: "Check local Monster sites where available.",
  },
  {
    name: "CareerBuilder",
    url: "https://www.careerbuilder.com/",
    region: "United States",
    focus: "General",
    type: "Job board",
    goodFor: "US corporate, administrative, operations, and technical roles.",
    notes: "Helpful for broad searches outside only tech.",
  },
  {
    name: "SimplyHired",
    url: "https://www.simplyhired.com/",
    region: "United States",
    focus: "General",
    type: "Aggregator",
    goodFor: "Broad job discovery and salary browsing.",
    notes: "Good for checking whether roles are duplicated across boards.",
  },
  {
    name: "Talent.com",
    url: "https://www.talent.com/",
    region: "Global",
    coverageRegions: [
      "United States",
      "Canada",
      "United Kingdom",
      "Europe",
      "Australia",
      "India",
      "Asia Pacific",
      "Middle East",
      "Africa",
      "Latin America",
    ],
    focus: "General",
    type: "Aggregator",
    goodFor: "International job search with country-level coverage.",
    notes: "Useful when comparing similar roles across countries.",
  },
  {
    name: "Jooble",
    url: "https://jooble.org/",
    region: "Global",
    coverageRegions: [
      "United States",
      "Canada",
      "United Kingdom",
      "Europe",
      "Australia",
      "India",
      "Asia Pacific",
      "Middle East",
      "Africa",
      "Latin America",
    ],
    focus: "General",
    type: "Aggregator",
    goodFor: "Global job aggregation, including smaller regional boards.",
    notes: "Search by country or city to reduce noise.",
  },
  {
    name: "Jora",
    url: "https://www.jora.com/",
    region: "Global",
    coverageRegions: ["Canada", "United Kingdom", "Australia", "India", "Asia Pacific"],
    focus: "General",
    type: "Aggregator",
    goodFor: "International job search with strong APAC coverage.",
    notes: "Owned by SEEK and often useful outside North America.",
  },
  {
    name: "Adzuna",
    url: "https://www.adzuna.com/",
    region: "Global",
    coverageRegions: ["United States", "Canada", "United Kingdom", "Europe", "Australia"],
    focus: "General",
    type: "Aggregator",
    goodFor: "Salary-aware searches and market snapshots.",
    notes: "Good when you want compensation signals while searching.",
  },
  {
    name: "Handshake",
    url: "https://joinhandshake.com/students/",
    region: "Global",
    coverageRegions: ["United States", "Canada", "United Kingdom", "Europe"],
    focus: "Campus",
    type: "Campus network",
    goodFor: "Students, recent graduates, internships, co-ops, entry-level jobs, and campus recruiting events.",
    notes: "Many universities use Handshake; access can depend on your school account.",
  },
  {
    name: "Symplicity CSM",
    url: "https://www.symplicity.com/uk/csm",
    region: "Global",
    coverageRegions: ["United States", "Canada", "United Kingdom", "Europe", "Australia", "Asia Pacific"],
    focus: "Campus",
    type: "Campus platform",
    goodFor: "University career-center job boards, employer postings, appointments, fairs, and internship workflows.",
    notes: "Often appears under a university-branded career portal rather than the Symplicity name.",
  },
  {
    name: "12twenty",
    url: "https://12twenty.com/",
    region: "Global",
    coverageRegions: ["United States", "Canada", "United Kingdom", "Europe"],
    focus: "Campus",
    type: "Campus platform",
    goodFor: "Early-career hiring through undergraduate, MBA, law, and alumni career programs.",
    notes: "Used by many school career centers and employer recruiting teams.",
  },
  {
    name: "GradConnection",
    url: "https://au.gradconnection.com/",
    region: "Global",
    coverageRegions: ["Australia", "India", "Asia Pacific"],
    focus: "Campus",
    type: "Graduate board",
    goodFor: "Graduate programs, internships, and student roles across multiple countries.",
    notes: "Especially useful for students and new graduates in APAC and international programs.",
  },
  {
    name: "FlexJobs",
    url: "https://www.flexjobs.com/",
    region: "Global",
    coverageRegions: [
      "United States",
      "Canada",
      "United Kingdom",
      "Europe",
      "Australia",
      "India",
      "Asia Pacific",
      "Middle East",
      "Africa",
      "Latin America",
    ],
    focus: "Remote",
    type: "Curated",
    goodFor: "Remote, hybrid, part-time, freelance, and flexible roles.",
    notes: "Curated listings; some features require a paid plan.",
  },
  {
    name: "We Work Remotely",
    url: "https://weworkremotely.com/",
    region: "Global",
    coverageRegions: [
      "United States",
      "Canada",
      "United Kingdom",
      "Europe",
      "Australia",
      "India",
      "Asia Pacific",
      "Middle East",
      "Africa",
      "Latin America",
    ],
    focus: "Remote",
    type: "Job board",
    goodFor: "Remote tech, design, product, marketing, support, and operations roles.",
    notes: "Best for remote-first searching without location-heavy noise.",
  },
  {
    name: "Remote OK",
    url: "https://remoteok.com/",
    region: "Global",
    coverageRegions: [
      "United States",
      "Canada",
      "United Kingdom",
      "Europe",
      "Australia",
      "India",
      "Asia Pacific",
      "Middle East",
      "Africa",
      "Latin America",
    ],
    focus: "Remote",
    type: "Job board",
    goodFor: "Remote technology, product, marketing, and startup roles.",
    notes: "Has a public API, useful for automation prototypes.",
  },
  {
    name: "Remotive",
    url: "https://remotive.com/",
    region: "Global",
    coverageRegions: [
      "United States",
      "Canada",
      "United Kingdom",
      "Europe",
      "Australia",
      "India",
      "Asia Pacific",
      "Middle East",
      "Africa",
      "Latin America",
    ],
    focus: "Remote",
    type: "Job board",
    goodFor: "Remote roles with a clean public API for searching.",
    notes: "A practical source for scripts and prototypes.",
  },
  {
    name: "Remote.co",
    url: "https://remote.co/remote-jobs/",
    region: "Global",
    coverageRegions: [
      "United States",
      "Canada",
      "United Kingdom",
      "Europe",
      "Australia",
      "India",
      "Asia Pacific",
      "Middle East",
      "Africa",
      "Latin America",
    ],
    focus: "Remote",
    type: "Job board",
    goodFor: "Remote jobs and remote-work company research.",
    notes: "Good for curated remote listings and career advice.",
  },
  {
    name: "Himalayas",
    url: "https://himalayas.app/jobs",
    region: "Global",
    coverageRegions: [
      "United States",
      "Canada",
      "United Kingdom",
      "Europe",
      "Australia",
      "India",
      "Asia Pacific",
      "Middle East",
      "Africa",
      "Latin America",
    ],
    focus: "Remote",
    type: "Job board",
    goodFor: "Remote tech roles with company profiles and salary filters.",
    notes: "Useful for transparent remote company research.",
  },
  {
    name: "Wellfound",
    url: "https://wellfound.com/jobs",
    region: "Global",
    coverageRegions: ["United States", "Canada", "United Kingdom", "Europe", "India", "Asia Pacific", "Latin America"],
    focus: "Startup",
    type: "Network",
    goodFor: "Startup jobs, founder contact, salary, and equity transparency.",
    notes: "Strong for engineering, product, design, sales, and operations.",
  },
  {
    name: "YC Work at a Startup",
    url: "https://www.ycombinator.com/jobs",
    region: "Global",
    coverageRegions: [
      "United States",
      "Canada",
      "United Kingdom",
      "Europe",
      "Australia",
      "India",
      "Asia Pacific",
      "Middle East",
      "Africa",
      "Latin America",
    ],
    focus: "Startup",
    type: "Job board",
    goodFor: "Roles at Y Combinator startups.",
    notes: "Good for early-stage startup searches.",
  },
  {
    name: "Otta",
    url: "https://app.otta.com/",
    region: "Global",
    coverageRegions: ["United States", "Canada", "United Kingdom", "Europe"],
    focus: "Tech",
    type: "Matching",
    goodFor: "Curated technology-company matching and role discovery.",
    notes: "Useful when you prefer matching over keyword-only searching.",
  },
  {
    name: "Dice",
    url: "https://www.dice.com/",
    region: "United States",
    focus: "Tech",
    type: "Job board",
    goodFor: "US technology jobs, contract roles, and recruiter discovery.",
    notes: "Strong for software, data, infrastructure, and IT roles.",
  },
  {
    name: "Built In",
    url: "https://builtin.com/jobs",
    region: "United States",
    focus: "Tech",
    type: "Job board",
    goodFor: "US tech-company roles, especially in major startup hubs.",
    notes: "Good for comparing tech company benefits and culture.",
  },
  {
    name: "The Muse",
    url: "https://www.themuse.com/search/",
    region: "United States",
    focus: "Company research",
    type: "Research",
    goodFor: "Company profiles, culture research, and curated roles.",
    notes: "Helpful when company fit matters as much as role title.",
  },
  {
    name: "Eluta",
    url: "https://www.eluta.ca/",
    region: "Canada",
    focus: "General",
    type: "Aggregator",
    goodFor: "Canadian jobs, especially employer career-site postings.",
    notes: "Great supplement to LinkedIn and Indeed in Canada.",
  },
  {
    name: "Job Bank Canada",
    url: "https://www.jobbank.gc.ca/",
    region: "Canada",
    focus: "General",
    type: "Government",
    goodFor: "Canadian roles, labor-market information, and verified employers.",
    notes: "Good for location-specific Canadian searches.",
  },
  {
    name: "WorkBC",
    url: "https://www.workbc.ca/search-and-prepare-job/find-jobs",
    region: "Canada",
    focus: "General",
    type: "Government",
    goodFor: "British Columbia jobs and career resources.",
    notes: "Useful if you are searching near Vancouver or elsewhere in BC.",
  },
  {
    name: "UBC CareersOnline",
    url: "https://students.ubc.ca/career/campus-jobs/",
    region: "Canada",
    focus: "Campus",
    type: "University portal",
    goodFor: "UBC student jobs, Work Learn roles, volunteer opportunities, internships, and alumni postings.",
    notes: "Some postings require UBC CWL login; UBC also lists campus hiring programs and units.",
  },
  {
    name: "University of Toronto CLNx",
    url: "https://clnx.utoronto.ca/",
    region: "Canada",
    focus: "Campus",
    type: "University portal",
    goodFor: "University of Toronto student jobs, internships, events, appointments, and experiential learning.",
    notes: "Best for U of T students and alumni with access to the CLNx system.",
  },
  {
    name: "WaterlooWorks",
    url: "https://uwaterloo.ca/hire/recruit-waterloo/co-operative-education/co-op-hiring-process/waterlooworks",
    region: "Canada",
    focus: "Campus",
    type: "University portal",
    goodFor: "University of Waterloo co-op jobs, interviews, rankings, and employer recruiting.",
    notes: "A major source for Waterloo co-op opportunities; student access is school-managed.",
  },
  {
    name: "McGill myFuture",
    url: "https://www.mcgill.ca/caps/students/services/myfuture",
    region: "Canada",
    focus: "Campus",
    type: "University portal",
    goodFor: "McGill student and alumni job postings, events, advising, and career resources.",
    notes: "Useful for McGill students and alumni; access usually requires institutional login.",
  },
  {
    name: "SFU myExperience",
    url: "https://www.sfu.ca/students/career.html",
    region: "Canada",
    focus: "Campus",
    type: "University portal",
    goodFor: "Simon Fraser University student opportunities, co-op, career events, and advising.",
    notes: "Use alongside SFU faculty and co-op pages for program-specific roles.",
  },
  {
    name: "Western Connect",
    url: "https://www.uwo.ca/careers/",
    region: "Canada",
    focus: "Campus",
    type: "University portal",
    goodFor: "Western University student jobs, career appointments, employer events, and campus opportunities.",
    notes: "Good for Western students and alumni searching school-mediated postings.",
  },
  {
    name: "University of Alberta campusBRIDGE",
    url: "https://www.ualberta.ca/en/career-centre/index.html",
    region: "Canada",
    focus: "Campus",
    type: "University portal",
    goodFor: "University of Alberta career postings, advising, employer events, and experiential learning resources.",
    notes: "Campus-specific listings may require student or alumni login.",
  },
  {
    name: "Reed",
    url: "https://www.reed.co.uk/jobs",
    region: "United Kingdom",
    focus: "General",
    type: "Job board",
    goodFor: "UK jobs across industries and experience levels.",
    notes: "Includes permanent, contract, temporary, and part-time roles.",
  },
  {
    name: "Totaljobs",
    url: "https://www.totaljobs.com/",
    region: "United Kingdom",
    focus: "General",
    type: "Job board",
    goodFor: "UK job search across many sectors.",
    notes: "Part of The Stepstone Group.",
  },
  {
    name: "CV-Library",
    url: "https://www.cv-library.co.uk/",
    region: "United Kingdom",
    focus: "General",
    type: "Job board",
    goodFor: "UK roles, CV posting, and recruiter contact.",
    notes: "Useful for both office and technical roles.",
  },
  {
    name: "StepStone",
    url: "https://www.stepstone.com/",
    region: "Europe",
    focus: "General",
    type: "Job board",
    goodFor: "European job search through StepStone country sites.",
    notes: "Especially relevant in Germany, Belgium, Austria, and nearby markets.",
  },
  {
    name: "Xing Jobs",
    url: "https://www.xing.com/jobs",
    region: "Europe",
    focus: "General",
    type: "Network",
    goodFor: "German-speaking professional networking and job search.",
    notes: "Useful for Germany, Austria, and Switzerland.",
  },
  {
    name: "EURES",
    url: "https://eures.europa.eu/index_en",
    region: "Europe",
    focus: "General",
    type: "Government",
    goodFor: "European Union job mobility and cross-border work.",
    notes: "Helpful for EU/EEA job-search research.",
  },
  {
    name: "SEEK",
    url: "https://www.seek.com.au/",
    region: "Australia",
    focus: "General",
    type: "Job board",
    goodFor: "Australia and New Zealand job search.",
    notes: "One of the strongest boards for Australia.",
  },
  {
    name: "Naukri",
    url: "https://www.naukri.com/",
    region: "India",
    focus: "General",
    type: "Job board",
    goodFor: "India jobs across tech, business, data, and operations.",
    notes: "One of India's biggest mainstream job boards.",
  },
  {
    name: "Instahyre",
    url: "https://www.instahyre.com/",
    region: "India",
    focus: "Tech",
    type: "Matching",
    goodFor: "Technology-company hiring and recruiter matching in India.",
    notes: "Good for software, data, and product roles.",
  },
  {
    name: "JobStreet",
    url: "https://www.jobstreet.com/",
    region: "Asia Pacific",
    focus: "General",
    type: "Job board",
    goodFor: "Southeast Asia job search.",
    notes: "Strong in Singapore, Malaysia, Philippines, and nearby markets.",
  },
  {
    name: "JobsDB",
    url: "https://hk.jobsdb.com/",
    region: "Asia Pacific",
    focus: "General",
    type: "Job board",
    goodFor: "Hong Kong and Asia Pacific roles.",
    notes: "Part of the SEEK ecosystem.",
  },
  {
    name: "Wanted",
    url: "https://www.wanted.co.kr/",
    region: "Asia Pacific",
    focus: "Tech",
    type: "Matching",
    goodFor: "Korea technology and startup roles.",
    notes: "Useful for Korea-focused tech searches.",
  },
  {
    name: "51job",
    url: "https://www.51job.com/",
    region: "China",
    focus: "General",
    type: "Job board",
    goodFor: "China jobs across industries.",
    notes: "Use Chinese keywords for best results.",
  },
  {
    name: "Zhaopin",
    url: "https://www.zhaopin.com/",
    region: "China",
    focus: "General",
    type: "Job board",
    goodFor: "China roles, graduate jobs, and corporate recruiting.",
    notes: "Useful for Mandarin-language job search.",
  },
  {
    name: "BOSS Zhipin",
    url: "https://www.zhipin.com/",
    region: "China",
    focus: "General",
    type: "Network",
    goodFor: "Direct chat with recruiters and hiring managers in China.",
    notes: "Often works more like a recruiting chat platform.",
  },
  {
    name: "Bayt",
    url: "https://www.bayt.com/",
    region: "Middle East",
    focus: "General",
    type: "Job board",
    goodFor: "Middle East and North Africa job search.",
    notes: "Strong for Gulf-region roles.",
  },
  {
    name: "GulfTalent",
    url: "https://www.gulftalent.com/",
    region: "Middle East",
    focus: "General",
    type: "Job board",
    goodFor: "Professional roles in the Gulf region.",
    notes: "Useful for UAE, Saudi Arabia, Qatar, and nearby markets.",
  },
  {
    name: "PNet",
    url: "https://www.pnet.co.za/",
    region: "Africa",
    focus: "General",
    type: "Job board",
    goodFor: "South Africa job search.",
    notes: "Good regional board for professional roles.",
  },
  {
    name: "Careers24",
    url: "https://www.careers24.com/",
    region: "Africa",
    focus: "General",
    type: "Job board",
    goodFor: "South African jobs across sectors.",
    notes: "Useful alongside LinkedIn and PNet.",
  },
  {
    name: "Bumeran",
    url: "https://www.bumeran.com/",
    region: "Latin America",
    focus: "General",
    type: "Job board",
    goodFor: "Latin America job search.",
    notes: "Coverage varies by country; use local Spanish keywords.",
  },
  {
    name: "Computrabajo",
    url: "https://www.computrabajo.com/",
    region: "Latin America",
    focus: "General",
    type: "Job board",
    goodFor: "Latin America roles across industries.",
    notes: "Good for broad regional searches.",
  },
  {
    name: "InfoJobs",
    url: "https://www.infojobs.net/",
    region: "Europe",
    focus: "General",
    type: "Job board",
    goodFor: "Spain-focused job search.",
    notes: "Useful for Spanish-language postings.",
  },
  {
    name: "Upwork",
    url: "https://www.upwork.com/",
    region: "Global",
    coverageRegions: [
      "United States",
      "Canada",
      "United Kingdom",
      "Europe",
      "Australia",
      "India",
      "Asia Pacific",
      "Middle East",
      "Africa",
      "Latin America",
    ],
    focus: "Freelance",
    type: "Marketplace",
    goodFor: "Freelance contracts across tech, design, writing, data, and business.",
    notes: "Best when you can package your skills into services; country and payment restrictions can apply.",
  },
  {
    name: "Toptal",
    url: "https://www.toptal.com/",
    region: "Global",
    coverageRegions: [
      "United States",
      "Canada",
      "United Kingdom",
      "Europe",
      "Australia",
      "India",
      "Asia Pacific",
      "Middle East",
      "Africa",
      "Latin America",
    ],
    focus: "Freelance",
    type: "Marketplace",
    goodFor: "Vetted freelance technology, design, product, and finance work.",
    notes: "More selective than general freelance platforms; availability can vary by client, role, and country.",
  },
  {
    name: "Contra",
    url: "https://contra.com/",
    region: "Global",
    coverageRegions: [
      "United States",
      "Canada",
      "United Kingdom",
      "Europe",
      "Australia",
      "India",
      "Asia Pacific",
      "Middle East",
      "Africa",
      "Latin America",
    ],
    focus: "Freelance",
    type: "Marketplace",
    goodFor: "Independent portfolio-based freelance work.",
    notes: "Good for design, creative, no-code, writing, and product services; payment access can vary by country.",
  },
];

export default function Home() {
  return <DirectoryClient jobBoards={jobBoards} />;
}
